ARDUINO_DIR  = /usr/share/arduino
BOARD_TAG    = mega2560 
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = SPI  Adafruit_GFX Adafruit_PCD8544 Ultrasonic Tone
include     /usr/share/arduino/Arduino.mk
AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf
